---
# This workflow integrates qwiet.ai preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: QwietAI-PreZero-Scan

permissions:
  actions: read
  contents: read
  security-events: write

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Check Dependencies with Gradle
      run: ./gradlew dependencies
      
    - name: Build with Gradle
      run: ./gradlew build
